package com.altintro.podium.utils

val NEW_USER = "NEW_USER"
val CONNECT_WITH_EMAIL = "EMAIL"
val CONNECT_WITH_FACEBOOK_NEW_USER = "FACEBOOK_NEW_USER"
val CONNECT_WITH_GOOGLE_NEW_USER = "GMAIL_NEW_USER"
val CONNECT_WITH_FACEBOOK = "FACEBOOK"
val CONNECT_WITH_GOOGLE = "GMAIL"
val INTENT_ACTION = "com.altintro.podium.activity.INTENT_ACTION"
val INTENT_MAGIC_LINK = "android.intent.action.VIEW"
